import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {betterAuth} from 'better-auth';
import {authOptions} from '../src/lib/auth-options';
import {hashAdminPassword,verifyAdminPassword} from '../src/lib/password';
async function main(){const dbUrl=new URL(process.env.MIGRATION_DATABASE_URL||process.env.DATABASE_URL!);const appUrl=new URL(process.env.BETTER_AUTH_URL!);assert.ok(['127.0.0.1','localhost'].includes(dbUrl.hostname)&&dbUrl.pathname==='/fa_local'&&['127.0.0.1','localhost'].includes(appUrl.hostname),'Security fixtures are restricted to the local development database and app.');const pool=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL||process.env.DATABASE_URL,max:1});let id:string|undefined;const jar=new Map<string,string>();const base=process.env.BETTER_AUTH_URL!;
async function call(path:string,body?:unknown){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Origin:base,Cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; ')},body:body?JSON.stringify(body):undefined});for(const c of response.headers.getSetCookie()){const [pair]=c.split(';');const i=pair.indexOf('=');jar.set(pair.slice(0,i),pair.slice(i+1));}const text=await response.text();return {status:response.status,data:text?JSON.parse(text):null};}
try{const email=`login-${randomUUID()}@example.com`,password=randomBytes(24).toString('base64url');const user=await betterAuth(authOptions(pool,true)).api.signUpEmail({body:{email,password,name:'Password login test'}});id=user.user.id;await pool.query('INSERT INTO fa_admins(user_id) VALUES($1)',[id]);assert.equal((await call('/api/auth/sign-in/email',{email,password,rememberMe:false})).status,200);
await call('/api/auth/sign-out',{});jar.clear();
// An account enrolled in an earlier release must now sign in with its password alone.
await pool.query('UPDATE "user" SET "twoFactorEnabled"=true WHERE id=$1',[id]);
assert.equal((await call('/api/admin/leads')).status,401);
assert.equal((await call('/api/auth/sign-in/email',{email,password:'incorrect-password',rememberMe:false})).status,401);
const login=await call('/api/auth/sign-in/email',{email,password,rememberMe:false});assert.equal(login.status,200);assert.equal(login.data.twoFactorRedirect,undefined);assert.equal((await call('/api/admin/leads')).status,200);
assert.equal((await call('/api/auth/two-factor/enable',{password,method:'totp'})).status,404);
const ttl=await pool.query('SELECT max(extract(epoch FROM ("expiresAt"-"createdAt"))) AS seconds FROM session WHERE "userId"=$1',[id]);assert.ok(Number(ttl.rows[0].seconds)<=28801);
const hash=await hashAdminPassword(password);assert.ok(await verifyAdminPassword({hash,password}));assert.equal(await verifyAdminPassword({hash,password:'wrong'}),false);
const runtime=new Pool({connectionString:process.env.DATABASE_URL,max:1});try{const role=(await runtime.query('SELECT rolsuper,rolcreatedb,rolcreaterole,rolbypassrls FROM pg_roles WHERE rolname=current_user')).rows[0];assert.ok(Object.values(role).every(v=>v===false));await assert.rejects(runtime.query('UPDATE fa_audit_events SET action=action WHERE false'),{code:'42501'});await assert.rejects(runtime.query('INSERT INTO fa_admins(user_id) VALUES($1)',[randomUUID()]),{code:'42501'});}finally{await runtime.end();}
await pool.query("UPDATE fa_admins SET role='editor' WHERE user_id=$1",[id]);assert.equal((await call('/api/admin/leads')).status,403);assert.equal((await call('/api/admin/blog')).status,200);await pool.query("UPDATE fa_admins SET role='admin' WHERE user_id=$1",[id]);
const search=await call('/api/admin/leads',{search:'Oliver',status:'',archived:'false',deleted:'false',range:'all',from:'',to:'',cursor:''});assert.equal(search.status,200);
const publicForm=(await call('/api/form')).data;const answers:Record<string,string|boolean>={};for(const field of publicForm.fields){answers[field.id]=field.type==='checkbox'?true:field.type==='select'?field.options[0]:field.type==='email'?'security-qa@example.com':field.type==='tel'?'2025550199':field.type==='date'?'2000-01-01':field.type==='number'?'1':field.id==='zipcode'?'10001':'Security QA synthetic';}
const requestId=randomUUID();try{const submitted=await call('/api/leads',{requestId,version:publicForm.version,source:'callback',answers,consent:true,website:''});assert.equal(submitted.status,201);assert.match(submitted.data.message,/submitted and saved/);const saved=(await pool.query('SELECT consent_text FROM fa_leads WHERE request_id=$1',[requestId])).rows[0];assert.match(saved.consent_text,/Submit request/);
const exp={search:'security-qa@example.com',status:'',archived:'false',deleted:'false',range:'time',from:new Date(Date.now()-600000).toISOString(),to:new Date(Date.now()+60000).toISOString()};
for(const format of ['csv','xlsx']){const response=await fetch(base+'/api/admin/leads/export',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:[...jar].map(([k,v])=>k+'='+v).join('; ')},body:JSON.stringify({...exp,format})});assert.equal(response.status,200);assert.equal(response.headers.get('X-Export-Count'),'1');assert.match(response.headers.get('cache-control')!,/no-store/);const bytes=Buffer.from(await response.arrayBuffer());if(format==='csv')assert.match(bytes.toString(),/security-qa@example.com/);else assert.equal(bytes.subarray(0,2).toString(),'PK');}
const denied=await fetch(base+'/api/admin/leads/export',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({...exp,format:'csv'})});assert.equal(denied.status,401);
}finally{await pool.query('DELETE FROM fa_leads WHERE request_id=$1',[requestId]);}
console.log('PASS: Password-only login for previously enrolled accounts, disabled MFA endpoints, 8-hour session cap, password verification and runtime privilege restrictions.');
}finally{if(id){await pool.query('DELETE FROM fa_request_limits WHERE false');await pool.query('DELETE FROM "user" WHERE id=$1',[id]);}await pool.end();}}
main().catch(error=>{console.error(error.message);process.exitCode=1;});
