"use client";
/* eslint-disable @next/next/no-img-element */
import { useRef, useState } from "react";
import { Save, Send, BookOpen, ImagePlus, X } from "lucide-react";
import { ArticleEditor, uploadBlogImage } from "./article-editor";
import { BlogContent } from "../blog-content";
import type { BlogDocument, BlogPost } from "@/lib/blog";
type Props={post:BlogPost;busy:boolean;dirty:boolean;update:(change:Partial<BlogDocument>)=>void;save:(status:BlogPost["status"])=>Promise<void>;setError:(message:string)=>void;back:()=>void};
export function BlogComposer({post,busy,dirty,update,save,setError,back}:Props){
 const [preview,setPreview]=useState(false);const [tag,setTag]=useState("");const [uploading,setUploading]=useState(false);const input=useRef<HTMLInputElement>(null);const doc=post.document;const hasCover=Boolean(doc.cover.trim());
 async function upload(file?:File){if(!file||uploading)return;setUploading(true);setError("");try{update({cover:await uploadBlogImage(file),coverAlt:file.name.replace(/\.[^.]+$/,""),credit:"",creditUrl:""});}catch(error){setError((error as Error).message);}finally{setUploading(false);}}
 function addTag(){const value=tag.trim();if(!value)return;const tags=doc.tags||[];if(tags.length>=12){setError("Use up to 12 tags.");return;}if(!tags.some(t=>t.toLowerCase()===value.toLowerCase()))update({tags:[...tags,value]});setTag("");}
 return <><div className="admin-blog-editor-actions"><button className="admin-button secondary" disabled={busy||uploading} onClick={back}>← All articles</button><span>{dirty?"Unsaved changes":`${post.status} · All changes saved`}</span></div><div className="blog-compose-layout"><div className="blog-compose-main"><label className="blog-title-label"><span className="sr-only">Article title</span><textarea rows={2} className="blog-title-input" placeholder="Add a title" value={doc.title} maxLength={160} disabled={busy} onChange={e=>{const title=e.target.value;const slug=(text:string)=>text.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");update({title,...(!post.id&&(!doc.slug||doc.slug===slug(doc.title))?{slug:slug(title)}:{})});}}/></label>
 {preview?<div className="admin-blog-preview"><h1 style={{fontSize:doc.titleSize,color:doc.titleColor}}>{doc.title}</h1><p>{doc.excerpt}</p>{hasCover&&<img src={doc.cover} alt={doc.coverAlt}/>}<BlogContent document={doc}/></div>:<ArticleEditor document={doc} disabled={busy||uploading} onChange={richContent=>update({richContent,blocks:[]})}/>}
 </div><aside className="blog-compose-sidebar"><section className="blog-settings-card"><h2>Publish</h2><div className="blog-publish-buttons"><button className="admin-button secondary" disabled={busy||uploading||(!dirty&&post.status==="draft")} onClick={()=>{if(post.status!=="published"||window.confirm("Move this article to draft? It will no longer be visible on the website."))void save("draft");}}><Save size={17}/>Draft</button><button className="admin-button" disabled={busy||uploading||(!dirty&&post.status==="published")} onClick={()=>save("published")}><Send size={17}/>{busy?"Saving…":"Publish"}</button></div><button className="blog-preview-button" onClick={()=>setPreview(!preview)}><BookOpen size={17}/>{preview?"Back to writing":"Preview article"}</button></section>
 <fieldset disabled={busy||uploading} className="blog-sidebar-fields"><section className="blog-settings-card"><h2>Category & tags</h2><label>Category<input list="blog-categories" value={doc.category} maxLength={60} onChange={e=>update({category:e.target.value})}/></label><datalist id="blog-categories">{["Family planning","Coverage basics","Family conversations","Practical guidance","Policy care"].map(value=><option key={value}>{value}</option>)}</datalist><label>Tags<div className="blog-tag-input"><input placeholder="Add a tag" value={tag} maxLength={40} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addTag();}}}/><button type="button" onClick={addTag}>Add</button></div></label><div className="blog-tags">{doc.tags?.map(value=><span key={value}>{value}<button aria-label={`Remove tag ${value}`} onClick={()=>update({tags:doc.tags?.filter(t=>t!==value)})}><X size={13}/></button></span>)}</div></section>
 <section className="blog-settings-card"><h2>Featured image</h2><button type="button" className="blog-cover-upload" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0]);}}>{hasCover&&<img src={doc.cover} alt={doc.coverAlt}/>}<span><ImagePlus size={22}/>{uploading?"Uploading…":hasCover?"Change featured image":"Add featured image"}<small>Drop an image or click to browse</small></span></button><input hidden ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value="";}}/><p className="blog-field-note">JPG · PNG · WebP · up to 5 MB</p><label>Image URL<input value={doc.cover} onChange={e=>update({cover:e.target.value})}/></label><label>Image description<input value={doc.coverAlt} maxLength={250} onChange={e=>update({coverAlt:e.target.value})}/></label><details><summary>Image credit & source</summary><label>Credit<input value={doc.credit} onChange={e=>update({credit:e.target.value})}/></label><label>Source link<input value={doc.creditUrl} onChange={e=>update({creditUrl:e.target.value})}/></label></details></section>
 <section className="blog-settings-card"><h2>Details</h2><label>Author<input value={doc.author} maxLength={100} onChange={e=>update({author:e.target.value})}/></label><label>Summary<textarea rows={4} value={doc.excerpt} maxLength={400} placeholder="A short introduction for the blog card" onChange={e=>update({excerpt:e.target.value})}/></label><label>URL slug<input value={doc.slug} onChange={e=>update({slug:e.target.value})}/></label><details><summary>Title appearance</summary><label>Title size<input type="number" min={28} max={72} value={doc.titleSize} onChange={e=>update({titleSize:Number(e.target.value)})}/></label><label>Title colour<input type="color" value={doc.titleColor} onChange={e=>update({titleColor:e.target.value})}/></label></details></section></fieldset>
 </aside></div></>;
}
