"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { blogSchema, newBlock, type BlogDocument, type BlogPost } from "@/lib/blog";
import { BlogComposer } from "./blog-composer";
import { useNotification } from "./notifications";
import { adminRequest } from "./dashboard";
type Row=Pick<BlogPost,"id"|"revision"|"slug"|"status"|"deleted_at"> & {title:string;category:string;cover:string};
export function BlogManager(){
 const [rows,setRows]=useState<Row[]>([]);const [page,setPage]=useState(1);const [hasMore,setHasMore]=useState(false);const [trash,setTrash]=useState(false);const [revision,setRevision]=useState(0);
 const [post,setPost]=useState<BlogPost|null>(null);const [original,setOriginal]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const {notify,dismiss}=useNotification();
 const dirty=Boolean(post&&JSON.stringify(post)!==original);
 useEffect(()=>{const controller=new AbortController();adminRequest(`/api/admin/blog?page=${page}&trash=${trash}`,{signal:controller.signal}).then(value=>{setRows(value.posts);setHasMore(value.hasMore);}).catch(error=>{if(!controller.signal.aborted)setError(error.message);});return()=>controller.abort();},[page,trash,revision]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 function update(change:Partial<BlogDocument>){setPost(current=>current?{...current,document:{...current.document,...change}}:current);dismiss();}
 function create(){const document:BlogDocument={title:"",slug:"",excerpt:"",category:"Family planning",author:"The Safe Quote Editorial Team",cover:"/images/blog/notebook.webp",coverAlt:"Notebook and pen",credit:"",creditUrl:"",titleSize:52,titleColor:"#214f5a",blocks:[newBlock()]};setPost({id:"",slug:"",document,status:"draft",revision:1,deleted_at:null,published_at:null});setOriginal("");setError("");dismiss();}
 async function open(id:string){setBusy(true);setError("");dismiss();try{const value=await adminRequest(`/api/admin/blog?id=${id}`);setPost(value);setOriginal(JSON.stringify(value));}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 async function save(status:BlogPost["status"]){if(!post)return;const parsed=blogSchema.safeParse(post.document);if(!parsed.success){setError(parsed.error.issues.map(issue=>`${issue.path.join(" ")}: ${issue.message}`).join(" · "));return;}const previous:BlogPost|null=post.id?JSON.parse(original):null;setBusy(true);setError("");try{const saved=await adminRequest("/api/admin/blog",{method:"POST",body:JSON.stringify({...(post.id?{id:post.id,revision:post.revision}:{}),status,document:parsed.data})});setPost(saved);setOriginal(JSON.stringify(saved));notify({title:saved.status==="published"?"Blog published":"Draft saved",message:saved.status==="published"?`“${saved.document.title}” is now live on your website.`:`“${saved.document.title}” has been saved as a draft.`,action:{label:"Undo",run:async()=>{if(previous){const restored=await adminRequest("/api/admin/blog",{method:"POST",body:JSON.stringify({id:saved.id,revision:saved.revision,status:previous.status,document:previous.document})});setPost(restored);setOriginal(JSON.stringify(restored));}else{await adminRequest("/api/admin/blog",{method:"PATCH",body:JSON.stringify({id:saved.id,revision:saved.revision,action:"delete"})});setPost(null);setOriginal("");}setRevision(value=>value+1);}}});setRevision(value=>value+1);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 async function remove(row:Row){if(!row.deleted_at&&!window.confirm(`Move “${row.title}” to Trash? You can restore it later.`))return;setBusy(true);setError("");try{await adminRequest("/api/admin/blog",{method:"PATCH",body:JSON.stringify({id:row.id,revision:row.revision,action:row.deleted_at?"restore":"delete"})});notify({title:row.deleted_at?"Blog restored":"Blog moved to Trash",message:`“${row.title}” ${row.deleted_at?"is available again.":"can be restored from Trash."}`,action:{label:"Undo",run:async()=>{await adminRequest("/api/admin/blog",{method:"PATCH",body:JSON.stringify({id:row.id,revision:row.revision+1,action:row.deleted_at?"delete":"restore"})});setRevision(value=>value+1);}}});setRevision(value=>value+1);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <section className="admin-section"><div className="admin-title"><div><span className="admin-eyebrow">THE JOURNAL</span><h1>{post?"Edit article":"Blog articles"}</h1><p>Write useful stories and make them your own.</p></div>{!post&&<button className="admin-button" onClick={create} disabled={busy}><Plus size={18}/>New article</button>}</div>{error&&<p className="admin-error" role="alert">{error}</p>}
 {!post?<><div className="admin-view-tabs"><button onClick={()=>{setTrash(false);setPage(1);}} aria-pressed={!trash}>Articles</button><button onClick={()=>{setTrash(true);setPage(1);}} aria-pressed={trash}>Trash</button></div><div className="admin-blog-list">{rows.map(row=><article key={row.id}>{row.cover&&<img className="admin-blog-thumbnail" src={row.cover} alt=""/>}<div className="admin-blog-row-copy"><span>{row.category} · {row.status}</span><h2>{row.title}</h2></div><div className="admin-actions">{!trash&&<><button className="admin-button secondary" onClick={()=>open(row.id)} disabled={busy}>Edit article</button>{row.status==="published"&&<a href={`/blog/${row.slug}`} target="_blank" className="admin-button secondary">View</a>}</>}<button className="admin-delete" onClick={()=>remove(row)} disabled={busy}>{trash?"Restore":"Delete"}</button></div></article>)}</div>{!rows.length&&<p>No articles here yet.</p>}<div className="admin-pagination"><button className="admin-button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button className="admin-button secondary" disabled={!hasMore} onClick={()=>setPage(page+1)}>Next</button></div></>:<>
 <BlogComposer key={post.id||"new"} post={post} busy={busy} dirty={dirty} update={update} save={save} setError={setError} back={()=>{if(!dirty||window.confirm("Discard unsaved article changes?")){setPost(null);setError("");}}}/></>}

 </section>;
}
