"use client";
import { useEffect, useState } from "react";
import { leadStatuses } from "@/lib/forms";
import { adminRequest } from "./dashboard";
const periods = [{value:"day",label:"Day",description:"Selected day"},{value:"week",label:"Week",description:"Selected week · Monday to Sunday"},{value:"month",label:"Month",description:"Selected month"},{value:"quarter",label:"3 Months",description:"Selected month and previous 2 months"},{value:"year",label:"Year",description:"Selected year"}];
const colors = { new:"#3876bb",contacted:"#bd8a26",qualified:"#278365",closed:"#7b60a5" };
type Breakdown = {period:string;anchor:string;today:string;start:string;end:string;total:number;statuses:Partial<Record<typeof leadStatuses[number],number>>;timezone:string};
export function StatusBreakdown({revision}:{revision:number}) {
 const [anchor,setAnchor]=useState("");const [draft,setDraft]=useState("");
 const [period,setPeriod]=useState("month");const [data,setData]=useState<Breakdown|null>(null);const [error,setError]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;const controller=new AbortController();adminRequest(`/api/admin/stats/status?period=${period}${anchor?`&date=${anchor}`:""}`,{signal:controller.signal}).then(value=>{if(active){setData(value);setDraft(current=>current||value.anchor);setError(false);}}).catch(()=>{if(active)setError(true);});return()=>{active=false;controller.abort();};},[period,anchor,revision,retry]);
 const pending=Boolean(data && (data.period!==period || (anchor && data.anchor!==anchor)));
 const selected=periods.find(item=>item.value===(data?.period||period))!;
 const date=(value:string)=>new Date(`${value}T12:00:00Z`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});
 let offset=0;const segments=leadStatuses.map(status=>{const start=offset;offset+=data?.total?(data.statuses[status]||0)/data.total*100:0;return `${colors[status]} ${start}% ${offset}%`;});
 return <article className="admin-chart admin-status-card"><h2>Status breakdown</h2><p>Analyse leads by the date they were received.</p><div className="admin-status-periods" role="group" aria-label="Status breakdown period">{periods.map(item=><button key={item.value} aria-pressed={period===item.value} onClick={()=>{if(period!==item.value){setPeriod(item.value);setError(false);}}}>{item.label}</button>)}</div>
 <form className="admin-status-picker" onSubmit={event=>{event.preventDefault();if(draft&&draft!==anchor){setAnchor(draft);setError(false);}}}>
 <label>{period==="day"?"Choose day":period==="week"?"Choose a date in the week":period==="quarter"?"Choose ending month":period==="year"?"Choose year":"Choose month"}
 {period==="year"?<input aria-label="Choose year" type="number" min={1900} max={2100} required value={draft.slice(0,4)} onInput={event=>setDraft(event.currentTarget.value?event.currentTarget.value+"-01-01":"")}/>:<input aria-label={period==="week"?"Choose a date in the week":period==="quarter"?"Choose ending month":period==="month"?"Choose month":"Choose day"} type={period==="month"||period==="quarter"?"month":"date"} min={period==="month"||period==="quarter"?"1900-01":"1900-01-01"} max={period==="month"||period==="quarter"?"2100-12":"2100-12-31"} required value={period==="month"||period==="quarter"?draft.slice(0,7):draft} onInput={event=>setDraft(event.currentTarget.value?(period==="month"||period==="quarter"?event.currentTarget.value+"-01":event.currentTarget.value):"")}/>}
 </label><button className="admin-button" type="submit" disabled={!draft}>Apply</button></form>
 {error?<div className="admin-status-message" role="alert">Could not load this period.<button className="admin-button secondary" onClick={()=>{setError(false);setRetry(value=>value+1);}}>Retry</button></div>:!data?<div className="admin-status-message" role="status">Loading {selected.label.toLowerCase()} data…</div>:<><div className="admin-status-range" aria-busy={pending}><span className="admin-period-loading" role="status">{pending?"Updating chart…":""}</span><strong>{selected.description}</strong><span>{date(data.start)}{data.start!==data.end?` – ${date(data.end)}`:""}</span></div><div className="admin-status-chart" aria-label={`${selected.description}: ${data.total} total leads`}><div className="admin-donut" aria-hidden="true" style={{background:data.total?`conic-gradient(${segments.join(",")})`:"#e5edf2"}}><div><strong>{data.total.toLocaleString()}</strong><span>Total leads</span></div></div><ul>{leadStatuses.map(status=><li key={status}><span><i style={{background:colors[status]}}/>{status.charAt(0).toUpperCase()+status.slice(1)}</span><strong>{data.statuses[status]||0}</strong></li>)}</ul></div><p className="admin-status-empty">{!data.total?"No leads received in this period.":" "}</p><p className="admin-status-timezone">{data.timezone} · Current lead statuses · {data.start<=data.today&&data.end>=data.today?"Period in progress":"Selected period"}</p></>}
 </article>;
}
