import type { Metadata } from "next";
import Link from "next/link";
import { plans } from "@/lib/content";
import { ClosingCta, Eyebrow, PageHero, PlanCards } from "@/components/sections";
import { Icon } from "@/components/icon";
import { Reveal } from "@/components/reveal";
import { HealthPlanOptions } from "@/components/health-plan-options";
export const metadata: Metadata = { title: "Medicare, supplemental & final expense coverage", description: "Explore Medicare Advantage, Medigap, Medicaid guidance, hospital indemnity, dental and vision, cancer insurance, and final expense coverage." };

export default function PlansPage() {
  return <><PageHero eyebrow="Our plans" title="Every family is different." accent="Your options should be, too." description="From Medicare and supplemental health coverage to final expense protection, understand your options and take your next step with confidence." /><HealthPlanOptions /><section className="section" id="final-expense-options"><div className="container"><div className="section-heading"><Eyebrow>Planning for the people you love</Eyebrow><h2>Final expense coverage.<br /><em>Thoughtful options for your family.</em></h2><p>Explore common plan structures for funeral costs and other final expenses.</p></div><PlanCards /><p className="section-footnote">These are examples of plan structures. Availability, eligibility, and benefits depend on your carrier, state, age, and health profile.</p></div></section><section className="section comparison-section"><div className="container"><Reveal><div className="section-heading centered"><Eyebrow>The details, side by side</Eyebrow><h2>See how the options <em>compare.</em></h2><p>A starting point for a helpful conversation with your licensed agent.</p></div><div className="comparison-scroll" tabIndex={0} role="region" aria-label="Scrollable plan comparison"><table className="comparison-table"><caption className="sr-only">Comparison of common final expense plan types</caption><thead><tr><th scope="col">What to consider</th>{plans.map(plan => <th key={plan.id} scope="col">{plan.icon && <Icon name={plan.icon} size={24} />}{plan.name}</th>)}</tr></thead><tbody>{[{ title: "Who it may suit", key: "fit" }, { title: "When benefits begin", key: "benefit" }, { title: "Health requirements", key: "health" }, { title: "Premium considerations", key: "cost" }].map(row => <tr key={row.key}><th scope="row">{row.title}</th>{plans.map(plan => <td key={plan.id}>{plan[row.key as "fit" | "benefit" | "health" | "cost"]}</td>)}</tr>)}</tbody></table></div><p className="section-footnote">Policy documents govern coverage. Ask about exclusions, waiting periods, benefit schedules, and premium guarantees before enrolling.</p></Reveal></div></section><section className="section"><div className="container planning-layout"><div><Eyebrow>Make room for the right questions</Eyebrow><h2>A plan that fits today.<br /><em>And the years ahead.</em></h2><p>Look beyond the coverage amount. A good conversation helps you understand what a policy means for you and your loved ones.</p><Link href="/quote" className="button">Explore my options <Icon name="arrow" size={18} /></Link></div><div className="planning-checklist">{["What monthly premium can I comfortably maintain?", "When do full benefits start?", "Which exclusions or limitations apply?", "How long are premiums guaranteed to stay the same?", "Who should I name as my beneficiary?"] .map((question, i) => <div key={question}><span>0{i + 1}</span><h3>{question}</h3><Icon name="check" size={19} /></div>)}</div></div></section><ClosingCta /></>;
}
